---
- name: Install Packages
  apt: name={{ item }} state=present
  with_items:
    - bareos-client

- name: Configure bareos client
  template: src=bareos-fd.conf dest=/etc/bareos/bareos-fd.conf mode=0640 owner=bareos group=bareos
  notify: reload bareos-client
  
- name: Enable bareos client service
  action: service name=bareos-fd state=started enabled=yes

