---
- name: Install Packages
  apt: name={{ item }} state=present
  with_items:
    - bareos-storage

- name: Create storage location
  file: path={{ storage_location }} owner=bareos group=bareos  mode=0770 state=directory

- name: Configure bareos storage
  template: src=bareos-sd.conf dest=/etc/bareos/bareos-sd.conf mode=0640 owner=bareos group=bareos
  notify: reload bareos-storage
  
- name: Enable bareos storage service
  action: service name=bareos-sd state=started enabled=yes

