---
- name: Install Packages
  apt: name={{ item }} state=present
  with_items:
    - bareos-director
    - bareos-database-postgresql
    - postgresql
    - bareos-bconsole
    
- name: enable postgresqld service
  action: service name=postgresql state=started enabled=yes 

- name: Push Bareos-Dir configuration file
  template: src=bareos-dir.conf dest=/etc/bareos/bareos-dir.conf mode=0640 owner=bareos group=bareos
  notify: reload bareos-dir

- name: Push bconsole configuration file
  template: src=bconsole.conf dest=/etc/bareos/bconsole.conf mode=0640 owner=root group=bareos

#Create baroes database
- name: create bareos database
  command:  su postgres -c /usr/lib/bareos/scripts/create_bareos_database
- name: create tables 
  command: su postgres -c /usr/lib/bareos/scripts/make_bareos_tables
- name: grant privs
  command: su postgres -c /usr/lib/bareos/scripts/grant_bareos_privileges
  
- name: enable bareos director service
  action: service name=bareos-dir state=started enabled=yes 
